### ISSUE TITLE
Cannot start the program and hangs in torch import of dover_features

### ISSUE THREAD

**Issue by vibhoothi** [Telecommunication-Telemedia-Assessment/frankenstone#1]
Hello,

Basically $TITLE,

Torch alone independently loads, but cannot run via dover_features.  The environment matches as what is suggested in readme. 

Was this observed in the past? 

Logs,
```bash
python3 frankenstone.py --help                                                                                      (frankenstone) 
2024-12-10 18:41:04.849194: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-12-10 18:41:04.856543: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1733856064.865364  434077 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1733856064.867898  434077 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-10 18:41:04.876903: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.



^C^C^C^C^C
Traceback (most recent call last):
  File "/media/colourloop/emerald/frankenstone/frankenstone.py", line 17, in <module>
    import dover_features
  File "/media/colourloop/emerald/frankenstone/dover_features.py", line 8, in <module>
    import torch
  File "/home/mindfreeze/miniconda3/envs/frankenstone/lib/python3.11/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

````

**Comment by stg7** [comment]
Hi, 
I will have a deeper look into it, I know that in the last month some issues occurred, and I will fix them.

**Comment by stg7** [comment]
Hi,

so I changed some of the requirements to have fixed versions (newer TF versions seem to create issues).
I also added a `prepare.sh` script to download missing models (dover and fastervqa).

I checked everything and now most of it should work.
Only NVENCC does not work, because the binary must match system libs.
So in theory it should work now.
Maybe you can check individual scripts (e.g. `dover_features.py`) for debugging.

best
Steve
